export const REQUEST_POSTS = 'REQUEST_POSTS';
export const FAILURE_POSTS = 'FAILURE_POSTS'
export const SUCCESS_POSTS = 'SUCCESS_POSTS'

export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const RATE_POST = 'RATE_POST';
export const FAILURE_ADD_POST = 'FAILURE_ADD_POST';
export const SUCCESS_ADD_POST = 'SUCCESS_ADD_POST';
export const SUCCESS_DELETE_POST = 'SUCCESS_DELETE_POST';
export const SUCCESS_RATING_POST = 'SUCCESS_RATING_POST';

export const EDIT_POST = 'EDIT_POST';
export const SORT_POST_BY = 'SORT_POST_BY';

export const REQUEST_COMMENTS_BY_POST = 'REQUEST_COMMENTS_BY_POST';
export const SUCCESS_LIST_COMMENTS = 'SUCCESS_LIST_COMMENTS';