export const REQUEST_POSTS = 'REQUEST_POSTS';
export const REQUEST_SINGLE_POST = 'REQUEST_SINGLE_POST';
export const FAILURE_POSTS = 'FAILURE_POSTS';
export const SUCCESS_POSTS = 'SUCCESS_POSTS';
export const SUCCESS_SINGLE_POST = 'SUCCESS_SINGLE_pOST';

export const FAILURE = 'FAILURE'

export const ADD_POST = 'ADD_POST';
export const EDIT_POST = 'EDIT_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const RATE_POST = 'RATE_POST';
export const SUCCESS_ADD_POST = 'SUCCESS_ADD_POST';
export const SUCCESS_EDIT_POST = 'SUCCESS_EDIT_POST';
export const SUCCESS_UPDATE_POST = 'SUCCESS_UPDATE_POST';
export const SUCCESS_DELETE_POST = 'SUCCESS_DELETE_POST';
export const SUCCESS_RATING_POST = 'SUCCESS_RATING_POST';
export const SORT_POST_BY = 'SORT_POST_BY';


export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const LIST_BY_CATEGORY = 'LIST_BY_CATEGORY';
export const SUCCESS_LIST_BY_CATEGORY = 'SUCCESS_LIST_BY_CATEGORY';
export const SUCCESS_REQUEST_CATEGORIES = 'SUCCESS_REQUEST_CATEGORIES';

export const REQUEST_COMMENTS_BY_POST = 'REQUEST_COMMENTS_BY_POST';
export const SUCCESS_LIST_COMMENTS = 'SUCCESS_LIST_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const RATE_COMMENT = 'RATE_COMMENT';
export const SUCCESS_ADD_COMMENT = 'SUCCESS_ADD_COMMENT';
export const SUCCESS_EDIT_COMMENT = 'SUCCESS_EDIT_COMMENT';
export const SUCCESS_UPDATE_COMMENT = 'SUCCESS_UPDATE_COMMENT';
export const SUCCESS_DELETE_COMMENT = 'SUCCESS_DELETE_COMMENT';
export const SUCCESS_RATING_COMMENT = 'SUCCESS_RATING_COMMENT';
export const SUCCESS_DELETE_ALL_COMMENTS = 'SUCCESS_DELETE_ALL_COMMENTS';
